<title>{shortname} ~ VIP Members</title>
<?php 
	$navigatorID = 2;
	require_once ('/includes/header.php');
	require_once ('/includes/navigator.php'); 
?>		
<script type="text/javascript">
function show2(id) {
	document.getElementById(id).style.visibility = "visible";
}
function hide2(id) {
	document.getElementById(id).style.visibility = "hidden";
}
</script>

<?php $rankcolor = 'red'; $rankid = 9; $getRanks = mysql_query("SELECT id,rank_name FROM permissions WHERE id = ".$rankid." ORDER BY id DESC"); while ($Ranks = mysql_fetch_assoc($getRanks)){ echo '<div class="col-md-6"><div class="card"><h1 class="title" style=""><div class="ripping"><img src="/game/c_images/album1584/GOATVIP.gif" style="float: right;margin-top: -25px;"></div><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Goat VIP</h1><div class="body" style="padding-bottom: 0px;"><div class="row1" style="height:280px;overflow-y:scroll;">';$getMembers = mysql_query("SELECT id,username,motto,look,online,account_created,last_online,country FROM users WHERE rank = '" . $Ranks['id'] . "' AND `rank` < '13' ORDER by last_online DESC");if (mysql_num_rows($getMembers) > 0) { $oe = 1; while ($member = mysql_fetch_assoc($getMembers)) { if($member['online'] == 0){ $OnlineStatus = "habbo_offline_big"; } else { $OnlineStatus = "online";} $Bans = mysql_query("SELECT null FROM `bans` WHERE `added_by` = '" . $member['username'] . "'"); $BanCount = mysql_num_rows($Bans); $Tickets = mysql_query("SELECT * FROM `moderation_tickets` WHERE `moderator_id` = '" . $member['id'] . "'"); $TicketsCount = mysql_num_rows($Tickets); echo ' <table width="100%"><tbody><tr><td valign="middle" width="25"><div style="position: relative; overflow:hidden; height:100px;"><img style="margin-top: -10px;" src="{imager}'.$member['look'].'&size=m&gesture=sml"></div></td><td valign="top"><td style="font-size: 90%; margin: 10px 0px 0px 0px;"><p><a href="/home/'.$member['username'].'"/><strong>'.$member['username'].'</strong></a></p><p style="padding: 0px;"><img src="{cdnurl}/images/motto.gif"/>&nbsp;'.$member['motto'].'</p><p><img src="{cdnurl}/images/login.gif"/>&nbsp;'; if(isset($OnlineStatus) && $OnlineStatus == 'online'){ echo 'Active right now!'; }else{ echo relativeTime($member['last_online']); } echo '</p></td></td><td valign="top" style="float: right;margin-right: 15px;"><img src="{cdnurl}/images/'.$OnlineStatus.'.gif"/><br/><img src="{cdnurl}/images/flags_small/'.$member['country'].'.png" title="Country"></td></tr></tbody></table><br>'; } } else{ echo '<div class="alert alert-danger" style="margin: 15px;"><center><b>No Goat VIP Members, Yet!</b></center></div>'; } echo '</font></font></h1></div></div></div></div> '; } ?>
<?php $rankcolor = 'red'; $rankid = 4; $getRanks = mysql_query("SELECT id,rank_name FROM permissions WHERE id = ".$rankid." ORDER BY id DESC"); while ($Ranks = mysql_fetch_assoc($getRanks)){ echo '<div class="col-md-6"><div class="card"><h1 class="title" style=""><div class="ripping"><img src="/game/c_images/album1584/FVIP.gif" style="float: right;margin-top: -25px;"></div><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Fendi VIP</h1><div class="body" style="padding-bottom: 0px;"><div class="row1" style="height:280px;overflow-y:scroll;">';$getMembers = mysql_query("SELECT id,username,motto,look,online,account_created,last_online,country FROM users WHERE rank = '" . $Ranks['id'] . "' AND `rank` < '13' ORDER by last_online DESC");if (mysql_num_rows($getMembers) > 0) { $oe = 1; while ($member = mysql_fetch_assoc($getMembers)) { if($member['online'] == 0){ $OnlineStatus = "habbo_offline_big"; } else { $OnlineStatus = "online";} $Bans = mysql_query("SELECT null FROM `bans` WHERE `added_by` = '" . $member['username'] . "'"); $BanCount = mysql_num_rows($Bans); $Tickets = mysql_query("SELECT * FROM `moderation_tickets` WHERE `moderator_id` = '" . $member['id'] . "'"); $TicketsCount = mysql_num_rows($Tickets); echo ' <table width="100%"><tbody><tr><td valign="middle" width="25"><div style="position: relative; overflow:hidden; height:100px;"><img style="margin-top: -10px;" src="{imager}'.$member['look'].'&size=m&gesture=sml"></div></td><td valign="top"><td style="font-size: 90%; margin: 10px 0px 0px 0px;"><p><a href="/home/'.$member['username'].'"/><strong>'.$member['username'].'</strong></a></p><p style="padding: 0px;"><img src="{cdnurl}/images/motto.gif"/>&nbsp;'.$member['motto'].'</p><p><img src="{cdnurl}/images/login.gif"/>&nbsp;'; if(isset($OnlineStatus) && $OnlineStatus == 'online'){ echo 'Active right now!'; }else{ echo relativeTime($member['last_online']); } echo '</p></td></td><td valign="top" style="float: right;margin-right: 15px;"><img src="{cdnurl}/images/'.$OnlineStatus.'.gif"/><br/><img src="{cdnurl}/images/flags_small/'.$member['country'].'.png" title="Country"></td></tr></tbody></table><br>'; } } else{ echo '<div class="alert alert-danger" style="margin: 15px;"><center><b>No Fendi VIP Members, Yet!</b></center></div>'; } echo '</font></font></h1></div></div></div></div> '; } ?>
<?php $rankcolor = 'red'; $rankid = 3; $getRanks = mysql_query("SELECT id,rank_name FROM permissions WHERE id = ".$rankid." ORDER BY id DESC"); while ($Ranks = mysql_fetch_assoc($getRanks)){ echo '<div class="col-md-6"><div class="card"><h1 class="title" style=""><div class="ripping"><img src="/game/c_images/album1584/PVIP.gif" style="float: right;margin-top: -25px;"></div><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Prada VIP</h1><div class="body" style="padding-bottom: 0px;"><div class="row1" style="height:280px;overflow-y:scroll;">';$getMembers = mysql_query("SELECT id,username,motto,look,online,account_created,last_online,country FROM users WHERE rank = '" . $Ranks['id'] . "' AND `rank` < '13' ORDER by last_online DESC");if (mysql_num_rows($getMembers) > 0) { $oe = 1; while ($member = mysql_fetch_assoc($getMembers)) { if($member['online'] == 0){ $OnlineStatus = "habbo_offline_big"; } else { $OnlineStatus = "online";} $Bans = mysql_query("SELECT null FROM `bans` WHERE `added_by` = '" . $member['username'] . "'"); $BanCount = mysql_num_rows($Bans); $Tickets = mysql_query("SELECT * FROM `moderation_tickets` WHERE `moderator_id` = '" . $member['id'] . "'"); $TicketsCount = mysql_num_rows($Tickets); echo ' <table width="100%"><tbody><tr><td valign="middle" width="25"><div style="position: relative; overflow:hidden; height:100px;"><img style="margin-top: -10px;" src="{imager}'.$member['look'].'&size=m&gesture=sml"></div></td><td valign="top"><td style="font-size: 90%; margin: 10px 0px 0px 0px;"><p><a href="/home/'.$member['username'].'"/><strong>'.$member['username'].'</strong></a></p><p style="padding: 0px;"><img src="{cdnurl}/images/motto.gif"/>&nbsp;'.$member['motto'].'</p><p><img src="{cdnurl}/images/login.gif"/>&nbsp;'; if(isset($OnlineStatus) && $OnlineStatus == 'online'){ echo 'Active right now!'; }else{ echo relativeTime($member['last_online']); } echo '</p></td></td><td valign="top" style="float: right;margin-right: 15px;"><img src="{cdnurl}/images/'.$OnlineStatus.'.gif"/><br/><img src="{cdnurl}/images/flags_small/'.$member['country'].'.png" title="Country"></td></tr></tbody></table><br>'; } } else{ echo '<div class="alert alert-danger" style="margin: 15px;"><center><b>No Prada VIP Members, Yet!</b></center></div>'; } echo '</font></font></h1></div></div></div></div> '; } ?>
<?php $rankcolor = 'red'; $rankid = 2; $getRanks = mysql_query("SELECT id,rank_name FROM permissions WHERE id = ".$rankid." ORDER BY id DESC"); while ($Ranks = mysql_fetch_assoc($getRanks)){ echo '<div class="col-md-6"><div class="card"><h1 class="title" style=""><div class="ripping"><img src="/game/c_images/album1584/XVIP.gif" style="float: right;margin-top: -25px;"></div><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Supreme VIP</h1><div class="body" style="padding-bottom: 0px;"><div class="row1" style="height:280px;overflow-y:scroll;">';$getMembers = mysql_query("SELECT id,username,motto,look,online,account_created,last_online,country FROM users WHERE rank = '" . $Ranks['id'] . "' AND `rank` < '13' ORDER by last_online DESC");if (mysql_num_rows($getMembers) > 0) { $oe = 1; while ($member = mysql_fetch_assoc($getMembers)) { if($member['online'] == 0){ $OnlineStatus = "habbo_offline_big"; } else { $OnlineStatus = "online";} $Bans = mysql_query("SELECT null FROM `bans` WHERE `added_by` = '" . $member['username'] . "'"); $BanCount = mysql_num_rows($Bans); $Tickets = mysql_query("SELECT * FROM `moderation_tickets` WHERE `moderator_id` = '" . $member['id'] . "'"); $TicketsCount = mysql_num_rows($Tickets); echo ' <table width="100%"><tbody><tr><td valign="middle" width="25"><div style="position: relative; overflow:hidden; height:100px;"><img style="margin-top: -10px;" src="{imager}'.$member['look'].'&size=m&gesture=sml"></div></td><td valign="top"><td style="font-size: 90%; margin: 10px 0px 0px 0px;"><p><a href="/home/'.$member['username'].'"/><strong>'.$member['username'].'</strong></a></p><p style="padding: 0px;"><img src="{cdnurl}/images/motto.gif"/>&nbsp;'.$member['motto'].'</p><p><img src="{cdnurl}/images/login.gif"/>&nbsp;'; if(isset($OnlineStatus) && $OnlineStatus == 'online'){ echo 'Active right now!'; }else{ echo relativeTime($member['last_online']); } echo '</p></td></td><td valign="top" style="float: right;margin-right: 15px;"><img src="{cdnurl}/images/'.$OnlineStatus.'.gif"/><br/><img src="{cdnurl}/images/flags_small/'.$member['country'].'.png" title="Country"></td></tr></tbody></table><br>'; } } else{ echo '<div class="alert alert-danger" style="margin: 15px;"><center><b>No Supreme VIP Members, Yet!</b></center></div>'; } echo '</font></font></h1></div></div></div></div> '; } ?>

</div>
</div>


<?php include_once('/includes/footer.php'); ?>
</body>
</html>